[build]
  command = "hugo --gc --minify --logLevel error -b $URL"
  publish = "public"

[build.environment]
  # Use site-local Hugo; Netlify will use the specified version if provided
  HUGO_VERSION = "0.148.2"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture --logLevel error -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify --logLevel error -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
